Repository OHDSI/Atlas, pull requests merged in 2020-08, with the labels that each got.

#2237 Added 'Copy Feature Analysis' functionality
  js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.html
  js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js
  js/pages/characterizations/services/FeatureAnalysisService.js
  js/pages/characterizations/services/PermissionService.js
Labels: July28-Aug10

#2240 Added tabs for system and user notifications (#2168)
  js/components/user-bar.html
  js/components/userbar/tabs/user-bar-jobs.html
  js/components/userbar/tabs/user-bar-jobs.js
  js/components/userbar/tabs/user-bar-jobs.less
  js/components/userbar/user-bar.html
  js/components/userbar/user-bar.js
  js/components/userbar/user-bar.less
  js/const.js
  js/services/JobDetailsService.js
  js/settings.js
Labels: July28-Aug10

#2236 Removed total CC page opacity
  js/components/cohortbuilder/components/CriteriaGroup.less
Labels: July28-Aug10

#2024 Ir link now opens report, Cohort link now opens report(#1819)
  js/components/analysisExecution/analysis-execution-list.html
  js/components/analysisExecution/analysis-execution-list.js
  js/components/atlas-state.js
  js/components/userbar/user-bar.js
  js/config/app.js
  js/const.js
  js/pages/Page.js
  js/pages/characterizations/components/characterizations/characterization-view-edit.js
  js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-exec-wrapper.js
  js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.html
  js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-executions.js
  js/pages/characterizations/routes.js
  js/pages/cohort-definitions/cohort-definition-manager.html
  js/pages/cohort-definitions/cohort-definition-manager.js
  js/pages/cohort-definitions/routes.js
  js/pages/estimation/cca-manager.js
  js/pages/estimation/components/cca-executions.html
  js/pages/estimation/components/cca-executions.js
  js/pages/estimation/routes.js
  js/pages/incidence-rates/components/iranalysis/components/report.js
  js/pages/incidence-rates/components/iranalysis/components/results.html
  js/pages/incidence-rates/components/iranalysis/components/results.js
  js/pages/incidence-rates/routes.js
  js/pages/pathways/components/manager.js
  js/pages/pathways/components/tabs/pathway-exec-wrapper.js
  js/pages/pathways/components/tabs/pathway-executions.html
  js/pages/pathways/components/tabs/pathway-executions.js
  js/pages/pathways/routes.js
  js/pages/prediction/components/prediction-executions.html
  js/pages/prediction/components/prediction-executions.js
  js/pages/prediction/prediction-manager.js
  js/pages/prediction/routes.js
  js/services/JobDetailsService.js
Labels: July28-Aug10

#2230 Disabled PLP & PLE components if lack of permissions
  js/components/atlas.cohort-editor.html
  js/components/cyclops/components/control-editor.html
  js/components/cyclops/components/control-editor.js
  js/components/cyclops/components/prior-editor.js
  js/components/featureextraction/components/covariate-settings-editor.html
  js/components/featureextraction/components/covariate-settings-editor.js
  js/extensions/bindings/contenteditableSwitch.js
  js/extensions/bindings/main.js
  js/pages/estimation/cca-manager.html
  js/pages/estimation/cca-manager.js
  js/pages/estimation/components/cca-specification-view-edit.html
  js/pages/estimation/components/cca-specification-view-edit.js
  js/pages/estimation/components/cca-specification-view-edit.less
  js/pages/estimation/components/cca-utilities.html
  js/pages/estimation/components/cca-utilities.js
  js/pages/estimation/components/editors/cohort-method-analysis-editor.html
  js/pages/estimation/components/editors/cohort-method-analysis-editor.js
  js/pages/estimation/components/editors/cohort-method-analysis.less
  js/pages/estimation/components/editors/comparison-editor.html
  js/pages/estimation/components/editors/match-args-editor.html
  js/pages/estimation/components/editors/match-args-editor.js
  js/pages/estimation/components/editors/negative-control-outcome-cohort-settings-editor.html
  js/pages/estimation/components/editors/negative-control-outcome-cohort-settings-editor.js
  js/pages/estimation/components/editors/outcome-model-args-editor.html
  js/pages/estimation/components/editors/outcome-model-args-editor.js
  js/pages/estimation/components/editors/positive-control-sythesis-settings-editor.html
  js/pages/estimation/components/editors/positive-control-sythesis-settings-editor.js
  js/pages/estimation/components/editors/stratify-args-editor.html
  js/pages/estimation/components/editors/stratify-args-editor.js
  js/pages/estimation/const.js
  js/pages/pathways/components/manager.js
  js/pages/prediction/components/editors/evaluation-settings-editor.html
  js/pages/prediction/components/editors/evaluation-settings-editor.js
  js/pages/prediction/components/editors/execution-settings-editor.html
  js/pages/prediction/components/editors/execution-settings-editor.js
  js/pages/prediction/components/editors/population-settings-editor.html
  js/pages/prediction/components/editors/population-settings-editor.js
  js/pages/prediction/components/editors/prediction-covariate-settings-editor.html
  js/pages/prediction/components/editors/prediction-covariate-settings-editor.js
  js/pages/prediction/components/prediction-specification-view-edit.html
  js/pages/prediction/components/prediction-specification-view-edit.js
  js/pages/prediction/components/prediction-specification-view-edit.less
  js/pages/prediction/const.js
  js/pages/prediction/prediction-manager.html
  js/pages/prediction/prediction-manager.js
Labels: Aug11-Aug24, July28-Aug10

#2220 Disabled incidence rate components if lack of permissions
  js/components/conceptsetbuilder/components/ConceptSetBuilder.js
  js/components/conceptsetbuilder/components/ConceptSetBuilderTemplate.html
  js/components/conceptsetbuilder/components/IncludedConcepts.js
  js/components/conceptsetbuilder/components/MappedConcepts.js
  js/pages/incidence-rates/components/iranalysis/components/editor.html
  js/pages/incidence-rates/components/iranalysis/components/editor.less
  js/pages/incidence-rates/components/iranalysis/components/results.html
  js/pages/incidence-rates/components/iranalysis/components/results.js
  js/pages/incidence-rates/ir-manager.html
Labels: Aug11-Aug24, July28-Aug10

#2281 Added vocab parameter to CS expression request
  js/services/ConceptSet.js
Labels: Aug11-Aug24

#2285 (#2284) PLP/PLE export error
  js/pages/estimation/cca-manager.js
  js/pages/prediction/prediction-manager.js
  js/services/Permission.js
Labels: Aug11-Aug24

#2269 Fixed FA action buttons state after the cancelation of removal
  js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js
Labels: Aug11-Aug24

#2262 Fixed caching of config api
  js/Application.js
  js/services/SourceAPI.js
Labels: Aug11-Aug24

#2183 merge geo spatial into 2.8
  js/config.js
  js/settings.js
  package.json
Labels: Aug11-Aug24, July28-Aug10

#2234 Issue 2167 add shared flag
  js/components/authorship.js
  js/components/circe/components/CohortConceptSetBrowser.js
  js/components/circe/components/CohortConceptSetBrowserTemplate.html
  js/components/cohort-definition-browser.js
  js/components/faceted-datatable.html
  js/components/faceted-datatable.js
  js/pages/characterizations/components/characterizations/characterization-view-edit.js
  js/pages/characterizations/components/characterizations/characterizations-list.js
  js/pages/characterizations/components/feature-analyses/const.js
  js/pages/characterizations/components/feature-analyses/feature-analysis-view-edit.js
  js/pages/cohort-definitions/cohort-definition-manager.js
  js/pages/concept-sets/components/conceptsets-export.js
  js/pages/concept-sets/conceptset-manager.js
  js/pages/estimation/cca-manager.js
  js/pages/estimation/estimation-browser.js
  js/pages/incidence-rates/components/iranalysis/components/browser.js
  js/pages/incidence-rates/ir-manager.js
  js/pages/pathways/components/browser.js
  js/pages/pathways/components/manager.js
  js/pages/prediction/prediction-browser.js
  js/pages/prediction/prediction-manager.js
  js/utils/DatatableUtils.js
Labels: Aug11-Aug24, July28-Aug10

#2198 cohort generation process and status is now visible to another users
  js/pages/cohort-definitions/cohort-definition-manager.html
  js/pages/cohort-definitions/cohort-definition-manager.js
Labels: Aug11-Aug24, Aug25-Sept7

#2289 Dropped legacy cohort features code
  js/pages/characterizations/components/characterizations/characterization-view-edit/characterization-results.js
  js/pages/cohort-definitions/cohort-definition-manager.js
  js/pages/cohort-definitions/components/cohortfeatures/FeatureSection.js
  js/pages/cohort-definitions/components/cohortfeatures/components/CohortFeatureBrowser.js
  js/pages/cohort-definitions/components/cohortfeatures/components/CohortFeatureBrowserTemplate.html
  js/pages/cohort-definitions/components/cohortfeatures/main.js
  js/pages/cohort-definitions/components/cohortfeatures/tableConfig/DemoTableColumns.js
  js/pages/cohort-definitions/components/cohortfeatures/tableConfig/DistributionTableColumns.js
  js/pages/cohort-definitions/components/cohortfeatures/tableConfig/DistributionTableOptions.js
  js/pages/cohort-definitions/components/cohortfeatures/tableConfig/DomainTableColumns.js
  js/pages/cohort-definitions/components/cohortfeatures/tableConfig/DomainTableFilteredColumns.js
  js/pages/cohort-definitions/components/cohortfeatures/tableConfig/DomainTableFilteredOptions.js
  js/pages/cohort-definitions/components/cohortfeatures/tableConfig/DomainTableOptions.js
  js/pages/cohort-definitions/components/cohortfeatures/tableConfig/FormattingOptions.js
  js/services/CohortFeatures.js
Labels: Aug25-Sept7

#2295 issue-907: added length of era plot to drug era board
  js/pages/data-sources/classes/Treemap.js
  js/pages/data-sources/components/reports/drugEra.js
  js/pages/data-sources/components/reports/treemap.html
  js/pages/data-sources/components/reports/treemapDrilldown.html
  js/pages/data-sources/components/reports/treemapDrilldown.js
Labels: Aug25-Sept7
